version: '3.7'

services:

  # Database
  db:
    image: postgres:12.1-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: always
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  # Nginx
  nginx:
    build:
      context: ./docker/nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_ROOT $$NGINX_HOST $$PHP_HOST $$PHP_PORT' < /etc/nginx/site.conf.tmpl > /etc/nginx/sites-available/site.conf && nginx -g 'daemon off;'"
    restart: always
    expose:
      - ${APP_PORT}
    working_dir: /etc/nginx
    environment:
      - VIRTUAL_HOST=${APP_HOST}
      - VIRTUAL_PORT=${APP_PORT}
      - VIRTUAL_NETWORK=proxy
      - HTTPS_METHOD=nohttps
      - NGINX_ROOT=${APP_PATH}
      - NGINX_HOST=${APP_HOST}
      - NGINX_PORT=${APP_PORT}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
    volumes:
      - ./log/nginx/:/var/log/nginx
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/site.conf.tmpl:/etc/nginx/site.conf.tmpl
      - /etc/nginx/sites-available
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - php
    links:
      - php:${PHP_HOST}
    networks:
      - proxy
      - default

  # PHP-FPM
  php:
    build:
      context: ./docker/php-fpm
      # args:
      #   - INSTALL_OPCACHE=false
      #   - INSTALL_XDEBUG=true
    container_name: ${COMPOSE_PROJECT_NAME}-php
    restart: always
    expose:
      - ${PHP_PORT}
    user: ${UID}:${GID}
    working_dir: ${APP_PATH}
    environment:
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}

  # Composer
  composer:
    build:
      context: ./docker/php-fpm
    container_name: ${COMPOSE_PROJECT_NAME}-composer
    entrypoint: composer
    restart: always
    user: ${UID}:${GID}
    working_dir: ${APP_PATH}
    environment:
      - UID=${UID}
      - GID=${GID}
      - COMPOSER_ALLOW_SUPERUSER=0
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER_AUTH=${COMPOSER_AUTH}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}

  # Artisan
  artisan:
    build:
      context: ./docker/php-fpm
    container_name: ${COMPOSE_PROJECT_NAME}-artisan
    entrypoint: php artisan
    restart: always
    user: ${UID}:${GID}
    working_dir: ${APP_PATH}
    environment:
      - UID=${UID}
      - GID=${GID}
    depends_on:
      - php
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}

volumes:
  db:
  pgadmin:

networks:
  proxy:
    external:
      name: proxy
